### ISSUE TITLE
adding more non-mandatory firewall profile options

### ISSUE THREAD

**Issue by heoelri** [theonlyway/xDSCFirewall#1]
@theonlyway we've used your xdscfirewall module to enable/disable firewall profiles. We would like to add some more firewall profile settings for logging etc. maybe it's possible to contribute to your project?

[xDSCFirewall.zip](https://github.com/theonlyway/xDSCFirewall/files/352330/xDSCFirewall.zip)

**Comment by theonlyway** [comment]
@heoelri Yeah by all means.

**Comment by heoelri** [comment]
[xDSCFirewall_20072016.zip](https://github.com/theonlyway/xDSCFirewall/files/373598/xDSCFirewall_20072016.zip)

**Comment by heoelri** [comment]
[xDSCFirewall_20072016.zip](https://github.com/theonlyway/xDSCFirewall/files/373606/xDSCFirewall_20072016.zip)

**Comment by theonlyway** [comment]
Cool I'll throw it in to another branch and do some testing then merge it in to the master when complete.

**Comment by theonlyway** [comment]
@heoelri I've tweaked it a bit, and have tested it in one of my labs successfully and it's currently passing CI tests. Are you able to test it in yours and let me know how you go?
