### ISSUE TITLE
 Suggest sending this into PS DSC Resource Kit's xNetworking repository

### ISSUE THREAD

**Issue by kewalaka** [theonlyway/xDSCFirewall#26]
Hi - would you be open to creating a pull request to include this as a resource in xNetworking?

Alternatively, if you'd like I'm happy to branch and do the PR paperwork assuming you're happy to relinquish copyright (required, to be allowed to submit your code under my Contributor License Agreement, I think).

Obviously, you'd get the credit :)

**Comment by theonlyway** [comment]
Hi,

Yeah I wouldn't mind going through the process as a learning experience. I assume I'd have to follow the stuff outlined here? https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md

Is there an issue on the xNetworking repo that I can reference?

**Comment by kewalaka** [comment]
@theonlyway that's great! I've posted an issue, happy to help if I can, though I don't claim to be an expert.

**Comment by theonlyway** [comment]
Unfortunately I didn't get around to doing this but someone else has already done it and merged in to https://github.com/PowerShell/xNetworking/pull/257
